spring.application.name=Elixir

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create

# JPA query log
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.properties.hibernate.use_sql_comments=true

# sql (always)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.groups-order=DESC
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.display-request-duration=true
springdoc.show-actuator=true
springdoc.packages-to-scan=BE_Elixir.Elixir
swagger.app.default-url=${DEFAULT_URL}

# jwt
jwt.secret={JWT_SECRET}
# 1?? (ms) 1000 * 60 * 60
jwt.access-token-validity=3600000
# 14? (ms) 1000 * 60 * 60 * 24 * 14
jwt.refresh-token-validity=1209600000

# redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# AWS S3
aws.accessKeyId=${AWS_ACCESSKEY}
aws.secretKey=${AWS_SECRETKEY}
aws.region=ap-northeast-2
aws.bucketName=s3elixir
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# permit all patterns
security.whitelist[0]=/test
security.whitelist[1]=/swagger-ui/*
security.whitelist[2]=/swagger-ui.html
security.whitelist[3]=/swagger-ui/**
security.whitelist[4]=/api-docs/**
security.whitelist[5]=/api/member/check-email
security.whitelist[6]=/api/member/signup
security.whitelist[7]=/api/auth/login
security.whitelist[8]=/api/ingredient
security.whitelist[9]=/api/ingredient/challenge
security.whitelist[10]=/api/member/update-password
security.whitelist[11]=/api/member/email-verification/verify
security.whitelist[12]=/api/member/email-verification
security.whitelist[13]=/actuator/health

# OpenAI api
openai.model=gpt-4o-mini
openai.secret-key=${OPENAI_SECRETKEY}

# naver
naver.id=${NAVER_ID}
naver.password=${NAVER_PW}

# health check
management.endpoints.web.exposure.include=health